### PR TITLE
🗃️ improve German translation

### PR DESCRIPTION
**Pull request by bitbrain**
The existing translation for German sounded a bit odd. As a native German speaker, I tried to make it a bit more natural sounding.

### CODE REVIEW

**Comment by bitbrain** [comment]
Do I have to manually generate the translation files? Or how does that work?

**Comment by coppolaemilio** [comment]
The editor generates those, but now that you remind me of this I think I need to add tons of new labels to the translation file. It is a bit hard to keep up with it 😅

**Comment by bitbrain** [comment]
@coppolaemilio I am happy to wait for those and provide the German translations as well!

**Comment by coppolaemilio** [comment]
I'll merge now to avoid conflicts later 👍🏻 
Thanks!

**Pull request merged**
