### PR TITLE
Allow RPG style portraits inside the text bubble

### PR DESCRIPTION
**Pull request by uzkbwza**
This allows the user to customize their theme to allow old-school RPG style portrait boxes *inside* the text area. this automatically hides the typical portraits and instead uses their data to display images inside a static frame.

image

https://user-images.githubusercontent.com/43023911/147336575-611d354f-c7f4-4a21-aece-44b2a5b0b28c.mp4

### CODE REVIEW

**Comment by coppolaemilio** [comment]
Hey, I'm testing the branch but I wasn't able to make it work properly. Other than enabling the settings on the theme is there any other thing I should set up? I'll now go over the code changes too, but "as a user" it wasn't working for me at this time.

**Comment by uzkbwza** [comment]
Currently it does not work in the theme preview - you have to test it in-game. Otherwise, did you make sure the character joins the scene? It works like a normal portrait - if the character does not join, their portrait will not be displayed.

**Comment by uzkbwza** [comment]
Apologies for all the force-pushing BTW, it's mostly rebase squashes. I haven't figured out an efficient way to test this without copying it from the test project back to the repo, which leads me to make silly mistakes.

**Comment by uzkbwza** [comment]
Just pushed an update fixing another bug that might have been causing you trouble; the portrait was only updating on text events. Now it will update on all of them.

**Comment by coppolaemilio** [comment]
new features now allow you to do this style of portraits, so I'm closing this pr

**Pull request closed without merging**
