### PR TITLE
added better Events navigation in docs.

### PR DESCRIPTION
**Pull request by RickWillcox**
Whilst reading the Help docs in Godot it was annoying to have to click back to help every time I wanted to go to a new event. 
example mp4 

https://user-images.githubusercontent.com/53924507/145822684-ef7a3c5e-f951-4c15-9dd7-77864a88cdaa.mp4

All I did was add links to the previous and next events in the list.

See my mp4 for it in action.

https://user-images.githubusercontent.com/53924507/145822362-54f96945-94a8-4ccb-b766-c24d5eb97308.mp4

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
Thanks for the PR!
I have nothing against this, just wondered why you didn't use the page selection in the Master Tree, where all the events are listed... 
grafik

Any particular reason why this is better?
I'm a bit concerend that this could be annoying to maintain.

**Comment by RickWillcox** [comment]
> Thanks for the PR! I have nothing against this, just wondered why you didn't use the page selection in the Master Tree, where all the events are listed... grafik
> 
> Any particular reason why this is better? I'm a bit concerend that this could be annoying to maintain.

Honestly didnt know that existed!

**Comment by Jowan-Spooner** [comment]
> Honestly didnt know that existed!
Would you say that fixes it for you? Or do you think we should still add these navigation links?

**Comment by RickWillcox** [comment]
I mean if I didnt know it existed I would assume I am not the only one. I think its probably a bit nicer to have links where my mouse currently is whilst scrolling. If it were my project I would add them :)

**Comment by coppolaemilio** [comment]
I'm closing this one and if we need better navigation we should fix the issue from the interface instead of each of the documentation files

**Pull request closed without merging**
