### PR TITLE
pretty print resources json with sorted keys

### LINKED ISSUE #269: Make resources more "git friendly"
**Is your feature request related to a problem? Please describe.**
Resources such as definitions and timelines are saved minimized, thus on the same line.
This makes working with git harder as each change will trigger a merge conflict.

**Describe the solution you'd like**
Pretty print JSON in the files. This will increase file size but maybe we can add a minify script that users can run before packing the game.

**Describe alternatives you've considered**
Right now I make sure only one person edits a timeline at the same time, but this is not practical.

### PR DESCRIPTION
**Pull request by arnaudvergnet**
This PR makes timelines and definitions easier to read and to handle with git. It also sorts object keys to prevent unnecessary changes when simply opening the timeline without modifying it in the editor.

The drawback is the file size, which increases because of the added characters. This PR does not provide any minifying script to run before packing the game.

Closes #269

### CODE REVIEW

**Comment by Sslaxx** [comment]
How much of a difference does it make file size?

**Comment by coppolaemilio** [comment]
negligible, we are talking less than a small sprite

**Comment by Sslaxx** [comment]
Pretty much what I thought, was wondering why it was listed as a concern in all honesty.

**Comment by coppolaemilio** [comment]
I believe Arnaud comes from webdev so in a website every byte counts :)

**Pull request merged**
