### PR TITLE
Add text speed multiplier

### PR DESCRIPTION
**Pull request by Jowan-Spooner**
This is usefull to have a settings slider. I'm not quite sure if it's what was meant but it could be a fix for #99

It adds two functions to the DialogicClass:

### Dialogic.set_text_speed_mutilplier(float)
0 = text shown instantly
smaller 1 = slower
1 = the normal speed (this is default)
bigger 1 = quicker
## Example
ezgif com-gif-maker
*the slider goes from 0 to 2*

### CODE REVIEW

**Comment by coppolaemilio** [comment]
Looks great! the only thing I would say at the moment is that 0 should be the slowest, and 2 should be instant. It is a bit weird to go back from super slow to instant so close in the slider and in the oposite side of what speed means

**Comment by Jowan-Spooner** [comment]
Hm yeah I could do that (would do it tomorrow). I choose this way as I thought it was what renpy's speed setting did. Also a speed of 0 (would take infinite time to show up). But we can discuss this again tomorrow.

**Comment by coppolaemilio** [comment]
@Jowan-Spooner This one was merged https://github.com/coppolaemilio/dialogic/pull/523, so I guess the branch would need an update.
Let me know if you want me to take over

**Comment by Jowan-Spooner** [comment]
This is way outdated. I personally still like the idea though, so maybe I'll find time to redo this in the future.

**Pull request closed without merging**
