### PR TITLE
Add contextual menus to add timelines, characters, definitions and themes

### PR DESCRIPTION
**Pull request by timkrief**
Peek 2021-04-12 23-39

### CODE REVIEW

**Comment by coppolaemilio** [comment]
I'm getting this error:  `res://addons/dialogic/Editor/MasterTree/MasterTree.gd:318 - Attempt to call function 'get_metadata' in base 'null instance' on a null instance.`

**Comment by timkrief** [comment]
> I'm getting this error: `res://addons/dialogic/Editor/MasterTree/MasterTree.gd:318 - Attempt to call function 'get_metadata' in base 'null instance' on a null instance.`

When are you getting this error?

**Comment by coppolaemilio** [comment]
This happens when I right click on one of the folders. I'm using the latest 3.3 rc.

**Comment by coppolaemilio** [comment]
I think the issue happens because the item never gets selected, so it cannot retrieve the metadata.

**Comment by timkrief** [comment]
I know what's happening, I think they change when the signals are triggered so now I end up deselecting before the rmb is triggered, and at this point, yes, nothing is selected so there's a bug. I'm on it

**Comment by timkrief** [comment]
Should work now and fixes the editable settings (and future item that should not be edited) at the same time

**Pull request merged**
