### PR TITLE
Text history

### PR DESCRIPTION
**Pull request by zaknafean**
Fixed a bug that prevented mouse clicks on choices

### CODE REVIEW

**Comment by coppolaemilio** [comment]
I'll try to fix the merge in this one and hopefully we can merge it soon. Kinda got shelved for too long, sorry about that.

**Comment by zaknafean** [comment]
No worries, I've been busy too. Will finalize things this week.

**Comment by zaknafean** [comment]
I have no idea why I'm getting such conflicts all over the place. It says over 40 files changed but it should be closer to 6. Can I safely 'delete' those file changes in some manner?

**Comment by zaknafean** [comment]
I think i'm gonna make a new PR for this Emilio, I don't like all the files it touched at this point and I can't seem to clean that up sufficently.

**Comment by coppolaemilio** [comment]
If you remember which files you modified on this PR you might be able to make a new PR from scratch. But if you want I could try to clean this branch 🤔

**Comment by zaknafean** [comment]
Ok copied things over pretty easily. I'm closing this, and this PR can be removed safely.

**Pull request closed without merging**
