### PR TITLE
Adding Nicknames (New Feature) and fixing auto-color names in text events

### PR DESCRIPTION
**Pull request by zakary93**
Hello, Emilio and everyone else! My name is Zak. I have been wanting to add **_Nicknames_** to the project since I tried it out. I call my friends nicknames and it is common in literature and video games as well, so I felt that naturally it should be included. I finally decided to do it myself and I hope everyone else can find some use for them as well as a feature! What this entails is this: **any Nicknames that you give to the character and enable in the editor will also follow auto-color rules**. If you don't have auto-color enabled it does nothing. This is also per character so each one doesn't need to have Nicknames (similar to display names). What is different is that these are not on the name tag and you will not need to go in and manually color nicknames in text events using BBCode. This could be expanded upon in the future with Nicknames having more functionality (although I don't know what, maybe branch it off into a different feature) but that is all at the moment. Here are some GIFs showing the changes to the editor and the functionality:
1) General conversation showing their nicknames and names at the same time
Nickname Showcase1
2) Showing changes to the Character Editor
Nickname Showcase2
3) Showing off adding more Nicknames (you just put a comma in-between on the _**Nicknames:**_ line edit)
Nickname Showcase3
4) Showing off that disabling it for one person only affects the Nicknames for that person. Everyone else continues to work.
Nickname Showcase4

Additionally, here is a screenshot where I show the previous issue with the names (this needed a fix regardless of this feature) and another with it fixed for comparison. As you can see the name should not be highlighted when part of another word:
Nickname Screenshot 5
Nickname Screenshot 6

Anyway, I thought this was neat and it seems to work well. I will be using this for my own games in the future (maybe not all of them but that is what makes it flexible) so I figured it would be something some people may want to use but obviously no one is required to use and doesn't impede on any existing functionality to do so (as far as I am aware). I hope you think it is worth adding as well. I love the project so far! To make it easier for you to go through, the files that were changed were: CharacterEditor.tscn (checkbox and line edit additions), CharacterEditor.gd, DialogicUtil.gd, and dialog_node.gd all had changes to accomplish this, though most were admittedly minor and nothing was really removed, just added to. 

_An additional note:_ 
I have not tried it on a small screen like 13" so I don't know if the additional checkbox will make it seem to cramped there since I only have a 17" and 27" and seems to fit right in for me on both just fine. Some testing may be needed and is easy to just change a checkbox position to underneath the display name checkbox or something if needed (any contributor can do this if they want).

Have a Great day!
-Zak

### CODE REVIEW

**Comment by coppolaemilio** [comment]
Looks good! I'll test it a bit and see if I can merge it

**Comment by zakary93** [comment]
Awesome! Looking forward to it!

**Comment by coppolaemilio** [comment]
Thank you! sorry for the delay 🙇‍♂️

**Comment by zakary93** [comment]
Its okay. Thanks for merging it in :)

**Pull request merged**
