### PR TITLE
Add Translation

### PR DESCRIPTION
**Pull request by magian1127**
[English translation and Google]
image

Editor plugin does not support tr().
So the method used [here](https://github.com/AnidemDex/Godot-TranslationService). https://github.com/AnidemDex/Godot-TranslationService
There is no translation of the place, is afraid to affect the existing function, the other places should be translated.

编辑器插件不支持tr()
所以用了[这里](https://github.com/AnidemDex/Godot-TranslationService)的方法.
没有翻译的地方,是怕影响现有功能,其他地方应该都翻译了.

### CODE REVIEW

**Comment by coppolaemilio** [comment]
This is great! I will review it and merge it as soon as possible.
谢谢 🙏

**Comment by magian1127** [comment]
You're welcome, I'm using it for my own use, so I'll "PR" it by the way.
The code may be a bit bad, it does not matter if you do not merge.

不客气,我自用的,就顺便"PR"了
代码可能有点烂,不合并也没关系.

**Comment by coppolaemilio** [comment]
I tried using it but I'm getting a lot of errors. Not sure what the solution is, but I will work on this and merge it 100%. I really want to get other languages on the plug-in but I need to do it in a way where it doesn't break when you update an existing project. Thanks for merging `main` again :)

我试着用它， 但我有很多错误。不知道解决方案是什么， 但我会努力， 并 100% 合并它。我真的很想让其他语言的插件，但我需要这样做的方式，它不会打破当你更新现有的项目。谢谢你再次合并 "主" :)

**Comment by magian1127** [comment]
image

It should be caused by missing or missing this file.
I tried to remove this file and load it, and I got the same error as you.

应该是缺少,或者没有找到这个文件导致的.
我尝试把这个文件移除后加载,得到的是和你一样的错误.

**Comment by coppolaemilio** [comment]
I have that file, but I still get the secondrun errors. Did you have to add something in settings to make it work? Because it seems like it is not finding the property `locale/translations` in the project settings.

我有那个文件，但我仍然收到第二次运行错误。 您是否必须在设置中添加某些内容才能使其正常工作？ 因为它似乎没有在项目设置中找到属性 `locale/translations`。 

image

**Comment by coppolaemilio** [comment]
I was able to make it work but I changed and removed many things. The function name is now `DTS` and the language settings is from the ` EditorSettings` instead of the `ProjectSettings`. Let me know if it works for you and feel free to make any extra changes. I will start working in the Spanish translation myself.

我能够使它的工作，但我改变了，并删除了很多事情。功能名称现在是"DTS"，语言设置来自"编辑设置"而不是"项目设置"。让我知道，如果它对你有效，并随时作出任何额外的改变。我将开始自己从事西班牙语翻译工作。

Thank you!! 🙌🏻

**Comment by magian1127** [comment]
The test is normal and no error is reported
测试正常,没有报错.

**Comment by wayrboy** [comment]
魔神,牛逼

**Pull request merged**
