### PR TITLE
adding filter to master tree

### PR DESCRIPTION
**Pull request by ellogwen**
This PR implements a filter box above the MainTree for searching your timelines, definitions, characters and themes as mentioned in issue #147

Showcase:
https://streamable.com/ejh4go

### CODE REVIEW

**Comment by coppolaemilio** [comment]
Looks great on the video! I'll review it right away 👍🏻

**Comment by ellogwen** [comment]
Found some bugs, will fix them now

**Comment by coppolaemilio** [comment]
Why did you make the MasterTreeContainer?

You don't need to bundle an image of the magnifier, you can find the icon in the editor itself. I use this addon that tells you how to access several parts of the theme:
https://github.com/pycbouh/godot-editor-theme-explorer

Check for the magnifier and it will give you a snippet of code to retrieve it :)

**Comment by ellogwen** [comment]
> Why did you make the MasterTreeContainer?
because adding the textbox directly to the tree as an item did not work property, so i needed a container. I can try to add it directly to the tree

> You don't need to bundle an image of the magnifier, you can find the icon in the editor itself. I use this addon that tells you how to access several parts of the theme:
> https://github.com/pycbouh/godot-editor-theme-explorer
> 
> Check for the magnifier and it will give you a snippet of code to retrieve it :)

i will

**Comment by coppolaemilio** [comment]
> because adding the textbox directly to the tree as an item did not work property, so i needed a container. I can try to add it directly to the tree
haha true, sorry I was confused for a second 🤦‍♂️

**Comment by coppolaemilio** [comment]
I found the code for the search icon:
`get_icon("Search", "EditorIcons")`

**Comment by ellogwen** [comment]
> I found the code for the search icon:
> `get_icon("Search", "EditorIcons")`

already changed it, but thank you :)

**Pull request merged**
