### PR TITLE
Refactor insert_variable_definition

### PR DESCRIPTION
**Pull request by theludovyc**
Working, it's can be merged =) !

### CODE REVIEW

**Comment by coppolaemilio** [comment]
What is the practical improvement over the previous existing code? Can you provide an example where the previous version wasn't working and this new one is?

**Comment by theludovyc** [comment]
Old version and New one works. It's just performance :)

**Comment by theludovyc** [comment]
Look at the code of replace https://github.com/godotengine/godot/blob/0cee8831b25377567bff8f46f7eaad8cb203dbf8/core/string/ustring.cpp#L3434

**Comment by Sslaxx** [comment]
Would rather see variable entries replaced with Dictionaries to allow more datatypes to be stored in them.

**Pull request closed without merging**
