### PR TITLE
Display multiple characters per TextBubble timer timout

### PR DESCRIPTION
**Pull request by dbackstr**
Added a new theme editor variable called "character_step" to represent how many characters should be displayed each time TextBubble.gd calls _on_writing_timer_timeout(), to facilitate faster apparent text display speeds.

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
Hi I like the idea of the changes but it looks to me, as if you also reintroduce a number of old theme settings, that shouldn't be there anymore. You might have to correct that.

**Comment by dbackstr** [comment]
I made these changes off of the distribution version-- 1.3, the one that comes from the asset library-- So any more recent changes, might not be reflected in my version. That might be the cause of reintroducing things that aren't meant to be there. What specifically is there that isn't meant to be there?

**Comment by Jowan-Spooner** [comment]
Yeah that is likely the cause. There are a couple of old theme settings that where removed, you can see it if you look at the changed files on github.

Not sure what the best to solve this is. As there is another PR changing the [speed] command right now, it might be the easiest to redo these changes from a clean branch, once the other one is merged.

**Comment by dbackstr** [comment]
hmm, in that case I'll close the pull request for now. maybe if I have some time I'll get the current master and see if I can re-implement the functionality.

**Pull request closed without merging**
