### PR TITLE
UndoRedo support for the TimelineEditor

### PR DESCRIPTION
**Pull request by Jowan-Spooner**
Created to solve #426 and #321.

Implemented with a local instance of godots UndoRedo.

By the time of writing this, it should work for:
- deleting events (with DELETE key)
- pasting events (CRTL+V)
- cutting events (CRTL+X)
- moving events (by dragging them)

When it messes up:
- if you do a not undoable action between these actions, the undo might do unexpected things (move the wrong item, etc.)

Future ideas:
- would love to make adding of events via the buttons and CRTL+T undoable, same goes for duplication. Also the option buttons and movement using ALT+Arrow keys. 

Please test this!

### CODE REVIEW

**Review by Schwender-exe — COMMENTED** [review]
Implemented changes and seems to work, though will have to test it a bit more to be 100% certain. Other than the CTRL D and CTRL Y command not implemented yet, works well!

**Review by Schwender-exe — CHANGES_REQUESTED** [review]
- CTRL D and CTRL Y commands
- as you stated before, undo/redo support when adding events to timeline
- (misc, but related to original issue) grab_focus when selecting choice event textbox

**Comment by Jowan-Spooner** [comment]
Thanks for testing. 

About Redo (CRTL+Y):
Actually in godot (at least for me, not sure if it's the same for you) Redo works with CRTL+SHIFT+Z. That should actually work already.

**Comment by Schwender-exe** [comment]
ah, that is in actually didn't notice, guess it's just because I'm using CTRL+Y for redoing actions, thanks though!

**Comment by Jowan-Spooner** [comment]
I've pushed a fix for CRTL+Y. Don't think it hurts.

**Comment by Jowan-Spooner** [comment]
Okay I finally managed to implement all the features I wanted for this now. Feel free to test again. Adding in events should be undoable as well as duplicating. I'll be away the next couple of days so if there's a problem you'll need to wait a bit.

**Comment by coppolaemilio** [comment]
I will test this now and see if I can merge to main

**Pull request merged**
