### PR TITLE
Plugin framework

### PR DESCRIPTION
**Pull request by KvaGram**
There is still some work to be done before this code is ready to merge into Dialogic.
But if you wish to test plugins, it's best done by using this code.

Currently, my audacity label importer plugin is ready to be tested.
https://github.com/KvaGram/KvaGram-Dialogic-plugins/tree/audacity-label.importer

Edits to this PR are welcome, just give me a heads-up.

### CODE REVIEW

**Comment by KvaGram** [comment]
Ah, that's an option? Well ok then. Thanks you.

**Comment by bitbrain** [comment]
Oh wow, this is exactly what I need for my project. I am using FMOD audio in my Godot project and won't be able to use the usual sound effects in Dialogic. I'll instead create a plugin for Dialogic that provides a custom Fmod sound effect node.

**Comment by KvaGram** [comment]
Indeed, @bitbrain. Features like using an external editor for the timeline is exacly the types of obscure features i am working on.
The plugin framework is still a work in progress, but once merged in, anyone can help with making new plugins for Dialogic.

**Comment by coppolaemilio** [comment]
I will close this PR because we are not going to keep improving the 1.4 branch at the moment. If you want to keep working on the 1.X branch there are still some bugs that need fixing but are not high priority; you can check the milestone: https://github.com/coppolaemilio/dialogic/milestone/7

Thanks!

**Pull request closed without merging**
