### PR TITLE
DialogNode.gd refactoring

### PR DESCRIPTION
**Pull request by SimplyBLGDev**
After trying to make some custom choice menu I realized the code is not exactly easy to read and I heard the owner of the project on one of his youtube videos saying that the new direction of Dialogic is to make it more accessible for extension.

That said I decided to start cleaning the code and refactoring on my way to understand the workings of the plugin; Here's the first part of that.

Some highlights:
+ Standarized style to more closely follow GDScript's suggested styling (did what I could without changing the names of variables and/or functions that could be being used outside the script as to not break compatibility)
+ + var example : type -> var example: type
+ + enum state -> enum STATE
+ + Spaced static dictionaries
+ + Separated some 'magic' values to constants
+ + Fixed mismatched indentation labels on empty lines
+ Replaced continuous invocations of $ operator to onready variables
+ Moved responsibility of next indicator visibility from DialogNode to TextBubble (simple wrapping)
+ Changed definition_visible to a setget variable (I noticed that every assignation to it did the same thing so I simplified the invocation)
+ Removed superfluous comments
+ Standardized comments spelling (Capitalization, spacing, maximum line length)
+ Separated obtuse functionality to their own functions (Increase modularity, reduce function line count, make methods more legible, makes functionality easier to find)
+ Removed unused update_custom_events() function
+ Rephrased some comments to better explain the code
+ Removed instances of internal developer banter from the code (Keep in the commits guys)
+ Replaced long chains of elifs to match statements
+Separated event handling to a function per type (way more legible and easier to modify)
+ Removed commented out code
+ Separated option creation to it's own _create_option(options) function, this will make overriding this functionality (like in my case) possible, further tweaking pending

There are still many very, very, very long functions that need to be decomposed further.
Some of the functionality that DialogNode.gd takes care of should be moved to children nodes, specially the Control node resizing/positioning, that behavior should be responsibility of the children nodes that have a script attached to them.

This same process needs to be applied to the rest of the scripts of the addon, but one step at a time.

### CODE REVIEW

**Comment by SimplyBLGDev** [comment]
I don't want this to be merged right away but I do want to start a discussion on refactoring to improve extensibility and readability.
I'll probably continue refactoring, let me know.

**Comment by Jowan-Spooner** [comment]
Hi, thanks for your work first of all.
the problem is that the development focus currently is on 2.0 which is basically a complete rewrite of the events and thus the dialog node.
the 1.x branch is currently maintained mainly by @zakary93, and we are mostly going for bug-fixes there.
So it's mostly his decision if he thinks it makes sense for these changes even tho 1.x won't be continued (at most get a few fixes) once 2.0 is out.
Your dedication is definitely appreciated tho. If you want, you can join emilios discord and discuss possible changes there, so no unnecessary work is done.
Just wanted to inform you about the state of affairs, this could still be merged.

**Comment by SimplyBLGDev** [comment]
Right, could you send me an invite to the server?

**Comment by Yotopihi-Dev** [comment]
https://discord.gg/zNkKBzcXED

**Comment by coppolaemilio** [comment]
Thanks for the effort and it looks like you really thought about stuff to be improved. Unfortunately this won't be merged since the 1.X branch is going to stay as is and we will continue working on the 2.0 branch. Feel free to get familiar with the new branch and see if you can contribute in that one instead since it is our top priority. If you want to keep working on the 1.X branch there are still some bugs that need fixing but are not high priority; you can check the milestone: https://github.com/coppolaemilio/dialogic/milestone/7

Thanks again!

**Pull request closed without merging**
