### PR TITLE
shortcuts for timeline navigation as of issue #46

### PR DESCRIPTION
**Pull request by ellogwen**
This PR implements two parts of the issue #46

selecting previous and next event in the timeline with `CTRL + UP` and `CTRL + DOWN`
moving currently selected event up and down the timeline `ALT + UP` and `ALT + DOWN`
This PR aswell automatically focuses the textbox when you select a TextEvent
This PR aswell automatically selects the event when you click into a TextEvent textbox

Preview Video:
https://streamable.com/i6nvah
(yes, I know there are typos in the video :P)

Edit: 
Indentation is now working on shortcut movement
`CTRL DELETE` removes the currently selected event node and selects the next/last event node
`CTRL T` creates a new text event node below the currently selected and focus it's textbox to continue writing

### CODE REVIEW

**Comment by ellogwen** [comment]
Indendation is missing when you move the block with shortcuts. I will fix this real quick

**Comment by arnaudvergnet** [comment]
Would it be possible to remove a selected item with the delete key? Or would it interfere with the rest of the editor?

**Comment by ellogwen** [comment]
> Would it be possible to remove a selected item with the delete key? Or would it interfere with the rest of the editor?

The delete key is a tricky one. A lot of interactions withing the editor uses the delete key and, inside a Text Event the delete key is part of a normal text edit workflow. Since this commit automatically selects the event panel in the timeline when you enter a Text Event text field, I dont know if it would be a good choice to chose the delete key.

**Comment by ellogwen** [comment]
Do not merge: Something is odd with the character selection and portrait selection of text events. Don't know if its my fault or the problem comes from somewhere else

**Comment by ellogwen** [comment]
Added `CTRL T` for creating a new text node below the current selected node and focusing it's textbox

**Comment by ellogwen** [comment]
There is a wonky behaviour with the alt down sometimes switching from the timeline down to the characters. not that big of a deal tho and i think the issue is within a default control behaviour of another element, not touched by this PR

**Comment by coppolaemilio** [comment]
Thank you so much!

**Pull request merged**
