### PR TITLE
Set Portrait via Definition (Variable)

### PR DESCRIPTION
**Pull request by bojjenclon**
Adds a new option to the portrait picker for "[Definition]". When selected, a new picker with the list of definition variables appears. When loading a portrait to show in-game, the variable will be evaluated and used to choose the portrait. This allows for dynamic portrait selection by changing this variable in code.

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
First of all: Nice that you did the work again. Please note that it is best practice to start a new branch if you start developing a new feature! Nevertheless, I will review your changes now, just keep it in mind!

**Comment by Jowan-Spooner** [comment]
It is mostly looking good, but I don't see a good way to set such a variable via the SetValue event... Maybe you should use "name" instead of "id" to identify them? or we should show the id in the character_editor next to the portrait (or a button to copy it into the clipboard). It would probably be possible to allow both name and id. 
What do you think @bojjenclon ?

**Comment by bojjenclon** [comment]
> First of all: Nice that you did the work again. Please note that it is best practice to start a new branch if you start developing a new feature! Nevertheless, I will review your changes now, just keep it in mind!

I normally do, just was rushing last night. My bad.

**Comment by coppolaemilio** [comment]
Thank you for this one! Sorry it took me so long to merge 😅

**Pull request merged**
