### PR TITLE
Audio Event and Background Music event update

### PR DESCRIPTION
**Pull request by Jowan-Spooner**
grafik

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
Should fix #211 and #151

**Comment by coppolaemilio** [comment]
I found some bugs if you really want to mess with them. But for what it's worth I'll approve it as is and then if someone really wants to break them they can create the bug reports. 

The only thing I would like changed is that they are open by default when you create them (like the text events) right now it seems weird that when you create an event you have to open it as well to start editing

**Comment by Jowan-Spooner** [comment]
@coppolaemilio You are right that is annoying. I did this because I found it annoying to have them be unfolded on default (when you open a timeline), because they just make it longer. I wanted to find out wether I can just open it when it's newly created, but didn't finish it. What do you think?

Do you like to be more specific about the bugs? Do you mean the problem if you delete the audio bus?

**Comment by coppolaemilio** [comment]
Ideally it should be like this anyway:
image
so even if it is closed you get the most important part of the editor, and if you want the extra options you can open it.

> Do you like to be more specific about the bugs? Do you mean the problem if you delete the audio bus?

It wasn't about the audio buses (didn't test it too much) It was regarding the order of the events. Like, if you create an event with background music 2s fadeout and the next event is another song with 0s fade, you will hear some weird things happening and the first event will "prevail". But again, I don't know why would anyone do that 🤷🏻‍♂️

**Comment by Jowan-Spooner** [comment]
Okay I updated it so that they are open by default.

**Pull request merged**
