### PR TITLE
Fixing requirement to manually configure export dialog

### PR DESCRIPTION
**Pull request by LuRomao**
Should fix proposal #393

### CODE REVIEW

**Comment by coppolaemilio** [comment]
Hey! this looks really nice, thank you for making it! One thing I don't understand: Is it adding every file? We only need it to add `.cfg` and `.json` files, but I don't see any filter to pick only those in the script 🤔

**Comment by LuRomao** [comment]
I think I forgot it, i'll add a filter

**Comment by LuRomao** [comment]
@coppolaemilio Here you go!

**Comment by coppolaemilio** [comment]
Thank you! I'll review it and merge it tonight 👌

**Comment by coppolaemilio** [comment]
It seems like some things are exporting properly, but the definitions don't seem to be working as intended. I will keep testing and see if there is any solution to that

**Pull request merged**
