### PR TITLE
Create variable if doesn't exist in `set_variable`

### PR DESCRIPTION
**Pull request by LoipesMas**
Does what `TODO` mentioned there. I hope that's the correct way to do this.

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
First of all, thanks for the contribution!
But... I'm not sure I like this change. I know emilio wrote that he would like this, but I feel like this could leed to very strange behaviour. 
I would definitely want to keep a notification in the output, because now you won't be notified if you made an typing mistake. 
Maybe both would be okay, but again, I personally don't know what the use behind this would be.

**Comment by zaknafean** [comment]
I'd definitely want this as an optional setting with a big warning. I can see where it would be handy if you're making lots of arbitrarily named variables in your game, but as a default behavior, it seems... dangerous.

**Comment by coppolaemilio** [comment]
Yeah, sorry if I was confusing on that comment, but I believe it would be nice to create "local" variables to create and use only in the context of that timeline. I don't think that it is a nice default behavior since it can create more problems that it would solve.

**Comment by LoipesMas** [comment]
Now that I think about it, I agree that it is a questionable idea at best. Because in the editor you can't use definitions that are not defined in the editor, so the only place that it would be useful would be for timelines generated at runtime, which I think is pretty niche.

**Pull request closed without merging**
