### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by theludovyc**
!!! This PR is a draft DO NOT MERGE IT !!!

Refactoring...

Today Changelog (Main changes)
- Add Test.gd
- Start splitting definitions in values and glossary
- Start removing use of loading files everytime (cost a lot)
- Start removing use of folder structure file

EditorView.gd
- Add class_name to use autocompletion
- Add res_values dictionary (contain editor's dialogic_values)
- Add timelines dictionary (new*)
- Add save_button (the greatest one, in futur add shortcut too)

MasterTree.gd
- Add values_tree
- new funcs to create trees and items

ValueEditor.gd
- Hide value name editor (new*)

DialogicResources.gd
- Add const working_dirs and cgf_files to increase perfomance and remove func get_working_dirs and get_cfg_files (call to func cost)
- Move init_dialogic_files in dialogic.gd (call to func cost)
- Add funcs to load and save values.json
- Add func to load timelines (new*)

DialogicSingleton.gd
- Add values dictionary (contain current value and default value)
- Add timelines dictionary (new*)

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
Hey @theludovyc, thanks for your contribution. I know this PR is not finished but here are some tips from me:
- please try to make your PR's as small as possible. If there are two seperate things to be done, do two PR's. This will highly increase the chances of your PR getting merged and not being stopped by one of the implementations being not finished or not how it's wanted.
- Another good thing is, to first name the problem and then discuss it. If you don't do it there is a high chance of you doing a lot of work just to find out, we discussed that before and decided otherwise. If you want to help, that's super cool. Either explain the problems you see in the PR or create issues for them before or join emilios discord to have a discussion about it.

While I like some of the changes you made, there are others where we already decided against. One is the use of match where it is not necessary. As it seems, match is slightly slower then a series of if statements (in godot), and it often even doesn't make things shorter. 

Anyways, I look forward to you contributing to this plugin. Just wanted to give you these tips, before you put in a lot of effort.

**Comment by theludovyc** [comment]
"As it seems, match is slightly slower then a series of if statements (in godot), and it often even doesn't make things shorter." I look at it. If it's true, it's really serious.

**Comment by theludovyc** [comment]
"please try to make your PR's as small as possible. If there are two seperate things to be done, do two PR's. This will highly increase the chances of your PR getting merged and not being stopped by one of the implementations being not finished or not how it's wanted."

I made a huge refactor and split it when you like something. See the changelog and sources :) !

**Comment by coppolaemilio** [comment]
It is true. It was confirmed by the devs. It is a small difference, but there is. Not a big deal though.

**Comment by theludovyc** [comment]
"Another good thing is, to first name the problem and then discuss it. If you don't do it there is a high chance of you doing a lot of work just to find out, we discussed that before and decided otherwise. If you want to help, that's super cool. Either explain the problems you see in the PR or create issues for them before or join emilios discord to have a discussion about it."

Ok, i'm coming on the discord :)

**Comment by theludovyc** [comment]
> It is true. It was confirmed by the devs. It is a small difference, but there is. Not a big deal though.

It's a big deal, beacause in any languages, match(switch) is there to increase performance and simplify code.
I'm sad to hear that.

**Comment by coppolaemilio** [comment]
I believe the issue is that the match statement also compares type. I'm sure it will be faster in the 4.X branch with the new GDScript, but even if so, the increase in performance in such a small `if`/`elif`/`else` statement vs a `match` is negligible.

**Pull request closed without merging**
