### PR TITLE
fixing bug with characters portrait size

### PR DESCRIPTION
**Pull request by ArtyKarty**
Founded a bug, that if you change game window size in project->project setting->window->size, the characters won't appear the right size

**cause**:
the TextureRect in Portrait.tsn is set up to size of the default screen size, with changing the screen size he now will be bigger/smaller then what he supposed to be.

example:
image

p.s don't check commits history I am just dumb

### CODE REVIEW

**Comment by coppolaemilio** [comment]
Is the change just those 4 lines? how did you manage to send all those commits? 🤣 

I'll review it tomorrow 👍🏻

**Comment by ArtyKarty** [comment]
That's how unexperienced I am with git XD

**Comment by Sslaxx** [comment]
You might want to look at squashing commits together? https://www.git-tower.com/learn/git/faq/git-squash/

**Comment by coppolaemilio** [comment]
This fix doesn't properly scale the images. I'm working on a fix for this issue at the moment

**Pull request closed without merging**
