### PR TITLE
Set Portrait via Definition (Variable)

### PR DESCRIPTION
**Pull request by bojjenclon**
Adds a new option to the portrait picker for "[Definition]". When selected, a new picker with the list of definition variables appears. When loading a portrait to show in-game, the variable will be evaluated and used to choose the portrait. This allows for dynamic portrait selection by changing this variable in code.

I'm not sure if anyone has ideas on how to do this "better," if so I'm very open to suggestions. If people approve of this approach, I still need to add it to the other events (it currently only shows up on Character Join events in the timeline). I figured it made sense to get input before modifying everything.

### CODE REVIEW

**Comment by coppolaemilio** [comment]
Whoops, I have bad news. @Jowan-Spooner is working on a pretty big overhaul of the events and I'm afraid I won't be able to easily include this changes at the moment. I really like the idea of allowing to set portraits based on that, but it will have to wait until those changes are merged and then you can try to solve the merge conflicts (or I can also try then).

If you want to know more about what things we are working on we are discussing this stuff on the discord server https://discord.gg/rycKdEVA

Sorry about that and hope you understand 😅

**Comment by bojjenclon** [comment]
Ah okay, good to know. I'll put this on hold until after the overhaul then. Thanks for letting me know.

**Comment by Jowan-Spooner** [comment]
Hey, I'm sorry to see that I'm blocking development. The mentioned changes will make all events come from the EventTemplate. All the functionality has been split into so called "EventParts", so your thing would have to added to the new PortraitPicker.
Please wait until friday before implementing your idea again. Sorry once again

**Comment by bojjenclon** [comment]
No worries! Hopefully I can bring this back afterward :)

**Pull request closed without merging**
