### PR TITLE
sort resources by name if available

### PR DESCRIPTION
**Pull request by arnaudvergnet**
This makes it easier to find resources using prefix, as discussed in #111.

Trees are rebuilt each time a resource name changes. I tried to squash every bugs I could find, but as always, test and report anything you find!

### CODE REVIEW

**Comment by coppolaemilio** [comment]
I'm getting all these errors on my existing test project
image

**Comment by coppolaemilio** [comment]
I'm a bit worried that every commit lately is breaking the existing projects, and this can be a big issue when people would be updating from 1.0 to 1.1

I feel like the singleton and having so many classes is starting to be a bit hard to manage, but I'll investigate to see what steps you need to make to upgrade without having issues.

**Comment by arnaudvergnet** [comment]
This commit should not be breaking changes, as it only impacts display. I managed to reproduce the issue and am working on a fix.

Having many classes is not especially a bad thing. It is better to have several classes with each their purpose than to regroup everything in one file.

The singleton seems to be quite annoying. It can only be used while running and if you change its name, you have to remove the previous one from project settings. But I don't know how you can keep saved data in memory without it.

**Comment by coppolaemilio** [comment]
> The singleton seems to be quite annoying. It can only be used while running and if you change its name, you have to remove the previous one from project settings. But I don't know how you can keep saved data in memory without it.

Yeah, I didn't want to add any singletons at first but when I started thinking about solutions to save the state of the custom made variables it became apparent that it would be impossible without actually having a persistent node in the game. Maybe there is a way to remove previous ones from code if they exists around here: https://github.com/coppolaemilio/dialogic/blob/25de662f782430689acae36ef08b0ca9d6989663/addons/dialogic/dialogic.gd#L11

**Comment by arnaudvergnet** [comment]
This should be fixed. For some reason godot was able to find the class used for sorting while I was working, but after a restart it couldn't find it anymore.

And if it can reassure you, I am working on my own game while contributing to the plugin, so any breaking change will impact me as well so I try to minimize them.

> Yeah, I didn't want to add any singletons at first but when I started thinking about solutions to save the state of the custom made variables it became apparent that it would be impossible without actually having a persistent node in the game. Maybe there is a way to remove previous ones from code if they exists around here: 

Might be worth investigating!

**Pull request merged**
